CREATE  TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    age int,
    email varchar(100)
);

INSERT INTO Person(name, age, email) VALUES ('Jack', 22, 'kola22@mail.com');
INSERT INTO Person(name, age, email) VALUES ('Bob', 25, 'bbq324@mail.com');
INSERT INTO Person(name, age, email) VALUES ('Mike', 26, 'mike5@mail.com');